---
"$schema": https://schema.felix-ern.de/ng-certificate-manager.schema.json
general:
  email: email@example.com
  additional_arguments: "--test-cert"
  plugins:
    - name: "backup-generated-certificate.sh"

certificates:
  - certificate_name: example.com
    additional_arguments: "--dns-ovh --dns-ovh-credentials /root/ovh/ovh-cred.ini"
    domains:
      - example.com
      - "*.example.com"
      - example.net
      - "*.example.net"
    plugins:
      - name: "install-on-server.sh"
        settings:
          deployment_hostname: "web01.example.com"
          deployment_username: "automation"
          deployment_dir: "/etc/ssl"

  - certificate_name: mail.example.com
    additional_arguments: "--dns-ovh --dns-ovh-credentials /root/ovh/ovh-cred.ini"
    domains:
      - mail.example.com
    plugins:
      - name: "install-on-server.sh"
        settings:
          deployment_hostname: "mail.example.com"
          deployment_username: "root"
          deployment_dir: "/etc/ssl"